services:
  - type: web
    name: the-void
    env: node
    plan: free
    autoDeploy: true
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: NODE_ENV
        value: production
      - key: VITE_SITE_URL
        sync: false
      - key: VITE_CLOUDINARY_BASE_URL
        sync: false
